// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery('#wowslider-container1').wowSlider({effect:"glass_parallax", prev:"", next:"", duration: 20*100, delay:20*100, width:960, height:360, autoPlay:true, autoPlayVideo:false, playPause:false, stopOnHover:false, loop:false, bullets:true, caption: true, captionEffect:"traces", controls:true, responsive:1, fullScreen:false, onBeforeStep:0, images:0 });